### ISSUE TITLE
read-only

### ISSUE THREAD

**Issue by ShalokShalom** [nspawn/nspawn.org#6]
Idk, if this is intentional, and if this is just missing on the homepage or an actual issue. 
I just downloaded archlinux-archlinux.tar, and it worked successful until the point, at that it refused to write anything. 

Inside the system, it reports it is a read-only filesystem - is this intended to be the case by default?
And outside of the system, I try to launch it via 

```
machinectl read-only archlinux-archlinux-tar false
```
And get this error message, despite that I am root: 
_Could not mark image read-only: Access denied_

**Comment by Edu4rdSHL** [comment]
`machinectl` sets the RO flag to all images imported with `pull-{tar,raw}` as a security measure because they are remote images. Our script actually takes care of that [here](https://github.com/nspawn/nspawn/blob/1fa9eaef39398bf591cf6a942956d4c436aba655/nspawn#L147). I can't reproduce the issue that you're describing about the access denied, please post your journal log after you get the error messages as well as the systemd version that you're using.

**Comment by ShalokShalom** [comment]
Wait, are you telling me, the nspawn.org images are all remote? So they dont execute on my PC, but do on your server?

And here is the journalctl: 
```

Feb 28 10:39:40 cosmos64 polkitd[492]: Registered Authentication Agent for unix-process:2141:53660 (system bus name :1.81 [/usr/bin/pkttyagent --notify-fd 5 --fallback], object path /org/freedesktop/PolicyKit1/AuthenticationAgent,>
Feb 28 10:39:40 cosmos64 polkit-kde-authentication-agent-1[782]: Listener adapter polkit_qt_listener_initiate_authentication
Feb 28 10:39:40 cosmos64 polkit-kde-authentication-agent-1[782]: GSimpleAsyncResult: 0x20b1910
Feb 28 10:39:40 cosmos64 polkit-kde-authentication-agent-1[782]: polkit_qt_listener_initiate_authentication callback for  0x2074e00
Feb 28 10:39:40 cosmos64 polkit-kde-authentication-agent-1[782]: Initiating authentication
Feb 28 10:39:40 cosmos64 polkit-kde-authentication-agent-1[782]: Message of action:  "Authentication is required to manage local virtual machine and container images."
Feb 28 10:39:40 cosmos64 polkit-kde-authentication-agent-1[782]: Action description has been found
Feb 28 10:39:40 cosmos64 polkit-kde-authentication-agent-1[782]: WinId of the dialog is  33554461 33554461
Feb 28 10:39:40 cosmos64 polkit-kde-authentication-agent-1[782]: WinId of the shown dialog is  33554461 33554461
Feb 28 10:39:40 cosmos64 polkit-kde-authentication-agent-1[782]: Trying again
Feb 28 10:39:40 cosmos64 polkit-kde-authentication-agent-1[782]: REQUEST
Feb 28 10:39:40 cosmos64 polkit-kde-authentication-agent-1[782]: Request:  "Password: "
Feb 28 10:39:40 cosmos64 polkit-kde-authentication-agent-1[782]: "Password: "
Feb 28 10:39:45 cosmos64 polkit-kde-authentication-agent-1[782]: Dialog accepted
Feb 28 10:39:45 cosmos64 polkit-kde-authentication-agent-1[782]: COMPLETED
Feb 28 10:39:45 cosmos64 polkit-kde-authentication-agent-1[782]: Completed:  true
Feb 28 10:39:45 cosmos64 polkit-kde-authentication-agent-1[782]: Finishing obtaining privileges
Feb 28 10:39:45 cosmos64 polkit-kde-authentication-agent-1[782]: Listener adapter polkit_qt_listener_initiate_authentication_finish
Feb 28 10:39:45 cosmos64 polkit-kde-authentication-agent-1[782]: polkit_qt_listener_initiate_authentication_finish callback for  0x2074e00
Feb 28 10:39:45 cosmos64 polkit-kde-authentication-agent-1[782]: Finish obtain authorization: true
Feb 28 10:39:45 cosmos64 polkitd[492]: Operator of unix-session:1 successfully authenticated as unix-user:shalok_shalom to gain TEMPORARY authorization for action org.freedesktop.machine1.manage-images for system-bus-name::1.82 [m>
Feb 28 10:39:45 cosmos64 polkitd[492]: Unregistered Authentication Agent for unix-process:2141:53660 (system bus name :1.81, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale C) (disconnected from bus)

```

And this is my systemd info: 

_Name            : systemd
Version         : 1:250.3-2
Description     : System and Session Manager
Architecture    : x86_64
URL             : http://www.freedesktop.org/wiki/Software/systemd
Licenses        : GPL2  LGPL2.1
Groups          : base
Provides        : udev=250.3  gummiboot
Depends On      : acl  bash  glibc  kmod  hwdata  util-linux  kbd  libcap  libxslt  iptables  linux-api-headers  pam  xz  libgcrypt  dbus  libidn2  lz4  quota  libseccomp  cryptsetup  pcre2  libxcrypt
Optional Deps   : libmicrohttpd: systemd-journal-gatewayd
Required By     : bluez  colord  cups  dracut  flatpak  libatasmart  libblockdev  libgudev  libgusb  libinput  libmbim  libusb  lvm2  media-player-info  mkinitcpio  modemmanager  ndctl  networkmanager  pcmciautils  polkit
                  pulseaudio  qt5-base  qt6-base  qtwebengine  rtkit  udisks2  upower  xf86-input-evdev  xf86-video-amdgpu  xorg-server
Optional For    : None
Conflicts With  : gummiboot
Replaces        : gummiboot
Installed Size  : 26.82 MiB
Packager        : Anke Boersma <demm@kaosx.us>
Build Date      : Tue Jan 18 20:27:01 2022
Install Date    : Thu Feb 10 20:38:33 2022
Install Reason  : Explicitly installed
Install Script  : Yes
Validated By    : SHA-256 Sum_

**Comment by ShalokShalom** [comment]
Same thing happens, if I download an image by your script: 

![Screenshot_20220228_170412](https://user-images.githubusercontent.com/6344099/156016547-0a909ffc-3863-4489-afca-93966738559b.png)

**Comment by Edu4rdSHL** [comment]
Honestly, it seems a problem with your filesystem... which filesystem are you using? Also, when I tell you to post the journal logs, please post the full logs, basically `journalctl -r -n 1000 |& curl --data-binary @- https://paste.rs/`

As you can see, I can not reproduce the issue:

![image](https://user-images.githubusercontent.com/32582878/156041163-2b9c316f-fbe6-4cf5-9777-88583a09a3af.png)

**Comment by ShalokShalom** [comment]
XFS

```
journalctl -r -n 1000 |& curl --data-binary @- https://paste.rs/                                                                                                                                               1 
<html>
<head><title>500 Internal Server Error</title></head>
<body bgcolor="white">
<center><h1>500 Internal Server Error</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by Edu4rdSHL** [comment]
For me, it's a problem with how `systemd-machined` manage the directory permissions on the XFS filesystem, please report it there if you are still experiencing the problem.
